"""Add status

Revision ID: 4448539f3aa7
Revises: b8874edcf0a4
Create Date: 2025-07-25 19:15:31.226917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4448539f3aa7'
down_revision = 'b8874edcf0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordatorio', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recordatorio_evento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'evento', ['evento_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordatorio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recordatorio_evento_id_fkey'), 'evento', ['evento_id'], ['id'])

    # ### end Alembic commands ###
