"""Modelo robusto para conciertos y pagos

Revision ID: 4ef520351378
Revises: a0a2123fce7f
Create Date: 2025-07-23 18:01:05.158430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef520351378'
down_revision = 'a0a2123fce7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('fecha_recordatorio', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('enviado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recordatorio')
    # ### end Alembic commands ###
