"""agregar imagen de asientos

Revision ID: 5ab5e24be499
Revises: 9b76700de28a
Create Date: 2025-07-22 15:58:38.667106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab5e24be499'
down_revision = '9b76700de28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_asientos', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('imagen_asientos')

    # ### end Alembic commands ###
