"""Add abonado to Pago

Revision ID: 9761b2d80059
Revises: 4ef520351378
Create Date: 2025-07-25 13:33:23.701923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9761b2d80059'
down_revision = '4ef520351378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abonado', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.drop_column('abonado')

    # ### end Alembic commands ###
