"""Modelo robusto para conciertos y pagos

Revision ID: a0a2123fce7f
Revises: cd9bd4277bbf
Create Date: 2025-07-23 12:10:38.772685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a2123fce7f'
down_revision = 'cd9bd4277bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('lugar',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('asientos',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('precio')

    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_pago', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('parcialidad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('evento_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('asiento',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('fecha_pago',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('monto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('ciudad', sa.String(length=100), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('plan_pago',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('plan_pago',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('ciudad')
        batch_op.drop_column('email')

    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('fecha_pago',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('asiento',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('evento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('notas')
        batch_op.drop_column('parcialidad')
        batch_op.drop_column('tipo_pago')

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('asientos',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('lugar',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
