"""Add status

Revision ID: a8b250a5d968
Revises: 4448539f3aa7
Create Date: 2025-07-25 20:21:32.022284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b250a5d968'
down_revision = '4448539f3aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portada', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('descripcion')
        batch_op.drop_column('portada')

    # ### end Alembic commands ###
