"""Add status

Revision ID: b8874edcf0a4
Revises: 9761b2d80059
Create Date: 2025-07-25 18:56:49.954456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8874edcf0a4'
down_revision = '9761b2d80059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus_pago', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.drop_column('estatus_pago')

    # ### end Alembic commands ###
