"""agregar evento_id y asiento a pagos

Revision ID: cd9bd4277bbf
Revises: e698084a26ca
Create Date: 2025-07-22 16:58:48.032544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9bd4277bbf'
down_revision = 'e698084a26ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precios_por_zona', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('precios_por_zona')

    # ### end Alembic commands ###
