"""agregar evento_id y asiento a pagos

Revision ID: e698084a26ca
Revises: 5ab5e24be499
Create Date: 2025-07-22 16:00:11.590457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e698084a26ca'
down_revision = '5ab5e24be499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evento_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('asiento', sa.String(length=50), nullable=True))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'evento', ['evento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('asiento')
        batch_op.drop_column('evento_id')

    # ### end Alembic commands ###
